// learn-react/06/1/src/components/CountButton.tsx
export default function CountButton ({
    increment, 
    decrement, 
    reset,
}: {
    increment: () => void;
    reset: () => void;
    decrement: () => void;
}) {
  return (
    
    <>
      <button onClick={decrement}>감소</button>
      <button onClick={reset}>0</button>
      <button onClick={increment}>증가</button>
    </>
  );
}

// learn-vue/student/06/src/components/CountButton.vue
<script setup>
import { useCountStore } from '@/stores/count'
// import { storeToRefs } from 'pinia'
const countStore = useCountStore()
// const { count } = storeToRefs(countStore)
const { decrement, reset, increment } = countStore
</script>
<template>
  <button @click="decrement">감소</button>
  <button @click="reset">0</button>
  <button @click="increment">증가</button>
</template>
<style scoped></style>
