// learn-vue/student/movies/vue/src/components/detail/DetailTrailer.vue
<script setup>

import { computed } from 'vue'

const props = defineProps({
  movieTrailer: Array,
  loading: Boolean,
})

const movieTrailer = computed(() => {
  if (props.movieTrailer?.length > 0 && props.movieTrailer[0].site && props.movieTrailer[0].key) {
    return props.movieTrailer[0].site.toLowerCase() === 'youtube' 
    ? 'https://www.youtube.com/embed/' + props.movieTrailer[0].key 
    : 'https://player.vimeo.com/video/' + props.movieTrailer[0].key
  }
  return null
})
</script>
  
<template>
  <section class="trailer">
    
    <iframe
    v-if="!props.loading && movieTrailer"
    width="900"
    height="506"
    :src="movieTrailer"
    title="YouTube video player"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
    allowfullscreen
    ></iframe>
    
    <iframe
      v-else
      class="skeleton-list-item"
      width="900"
      height="506"
      title="YouTube video player"
      frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
      allowfullscreen
    ></iframe>
  </section>
</template>
  
<style scoped>
  
</style>

// learn-next/tmdb/src/components/detail/DetailTrailer.tsx
import { getMovieData, getMovieVideoData } from "@/libs/api/movie";
import Image from "next/image";

export default async function DetailTrailer({ id }: { id: string }) {
  const [{ results: trailer }, detail] = await Promise.all([
    getMovieVideoData(id),
    getMovieData(id),
  ]);

  const filterTrailer = trailer[0] || null;
  return (
    <>
      <section className="trailer">
        {filterTrailer && (
          <iframe
            src={`https://www.youtube.com/embed/${filterTrailer.key}?si=FDVIRTdUuTZr3DgM`}
            title="YouTube video player"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowFullScreen
            style={{
              border: 0,
              width: "90%",
              maxWidth: "900px",
              aspectRatio: "16 / 9",
            }}
          ></iframe>
        )}
        {!filterTrailer && (
          <Image
            src={`https://image.tmdb.org/t/p/original/${detail.poster_path}`}
            alt="poster_path"
            width={900}
            height={0}
            style={{
              width: "90%",
              maxWidth: "900px",
              height: "auto",
              maxHeight: "500px",
            }}
          />
        )}
      </section>
    </>
  );
}
