// learn-vue/student/06_todoList_pinia/src/components/TodoList.vue
<script setup>
import TodoListItem from "./TodoListItem.vue";
import { useTodoStore } from "@/stores/todo";

const todoStore = useTodoStore();


</script>

<template>
  <ul class="divide-y divide-gray-200">
    <TodoListItem 
      v-for="todo in todoStore.todos" 
      :key="todo.id" 
      :todo="todo" 
    />
  </ul>
</template>

<style></style>

// learn-react/06/할일관리앱/src/components/TodoList.tsx
import TodoListItem from "./TodoListItem";

export default function TodoList({
  todos,
  toggleTodo,
  deleteTodo,
}: {
  todos: TodoItem[];
  toggleTodo: (id: number) => void;
  deleteTodo: (id: number) => void;
}) {
  
  return (
    <ul className="divide-y divide-gray-200">
      {/* && -> 조건부 렌더링 
        todos가 존재할 때만 todos.map(...)실행
        todos 배열을 순회하면서 <TodoListItem />을 여러 개 생성
      */}
      {todos && todos.map((todo) => (
          <TodoListItem
            key={todo.id}
            todo={todo}
            toggleTodo={toggleTodo}
            deleteTodo={deleteTodo}
          />
      ))}
    </ul>
  );
}
