// learn-vue/student/03/src/App.vue
<script>
import CountGroup from './components/CountGroup.vue'

export default {
  name: 'App',
  components: {
    CountGroup,
  },
  data() {
    return {
      count: 0,
    }
  },
  provide() {
    return {
      count: () => this.count,
      increment: this.increment,
      reset: this.reset,
      decrement: this.decrement,
      incrementByAmount: this.incrementByAmount,
    }
  },
  methods: {
    decrement() {
      this.count -= 1
    },
    reset() {
      this.count = 0
    },
    increment() {
      console.log('increment')
      this.count += 1
    },
    incrementByAmount(amonut) {
      this.count += amonut
    },
  },
}
</script>
<template>
  <CountGroup />
</template>
<style scoped></style>

// learn-react/07/3/src/App.tsx
import { useState } from "react";
import Count from "./components/Count";

export default function App () {

  console.log("App Component!");
  const [count, setCount] = useState(0);
  
  return (
    <>
      <h1>Count: {count}</h1>
      <button onClick={() => setCount((count) => count + 1)}>증가</button>
      <Count />
    </>
  );
}
