// learn-next/tmdb/src/components/main/MainBanner.tsx
import Link from "next/link";
import { getMovieData } from "@/libs/api/movie";

export default async function MainBanner() {
  const { results: movies }: { results: Movie[] } = await getMovieData(
    "upcoming"
  );

  const randomMovie = () => {
    const movieFilter = movies.filter(
      (movie) => movie.overview && movie.overview.trim() !== ""
    );
    const randomIndex = Math.floor(Math.random() * movieFilter.length);
    return movieFilter[randomIndex];
  };

  const random = randomMovie();
  console.log(random);
  return (
    <>
      <section className="release">
        <div
          className="release-item"
          style={{
            backgroundImage: `url('https://image.tmdb.org/t/p/w500/${random.poster_path}')`,
          }}
        >
          <div className="release__text">
            <strong className="release__category">NEW RELEASE</strong>
            <h2 className="release__title">{random.title}</h2>
            <p className="release__desc">{random.overview}</p>
            <Link href={`/detail/${random.id}`}>
              <button className="release__btn">자세히보기</button>
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}

// learn-vue/student/movies/vue/src/main/MainBanner.vue
<script setup>
import { computed } from 'vue'

const props = defineProps({
  movies: Array,
  loading: Boolean,
})

const randomMovie = computed(() => {
  if (!props.movies || props.movies.length === 0) return null

  const movieFilter = props.movies.filter((movie) => movie.overview && movie.overview.trim() !== '')
  if (movieFilter.length === 0) return null

  const randomIndex = Math.floor(Math.random() * movieFilter.length) // 0 ~ 19
  return movieFilter[randomIndex]
})
</script>
<template>
  <section v-if="!props.loading && randomMovie" class="release">
    <div
      class="release-item"
      :style="`background-image: url('https://image.tmdb.org/t/p/w500/${randomMovie.poster_path}')`"
    >
      <div class="release__text">
        <strong class="release__category">NEW RELEASE</strong>
        <h2 class="release__title">{{ randomMovie.title }}</h2>
        <p class="release__desc">
          {{ randomMovie.overview }}
        </p>
        <button class="release__btn">자세히보기</button>
      </div>
    </div>
  </section>
</template>
